name: Build IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Build App
        run: |
          xcodebuild build \
            -scheme airlift \
            -destination 'generic/platform=iOS' \
            -configuration Release \
            CODE_SIGNING_ALLOWED=NO \
            -derivedDataPath build

      - name: Package to IPA
        run: |
          mkdir -p Payload
          cp -r build/Build/Products/Release-iphoneos/*.app Payload/
          zip -r airlift-unsigned.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: airlift-ipa
          path: airlift-unsigned.ipa
